
spring:
  application:
    name: Intelligent-University-Visit-System
  datasource:
    url: jdbc:mysql://localhost:3306/uni_tour
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 2006051Chenyibo?
  data:
    redis:
      host: localhost
      port: 6379

#配置日志输出
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
