
spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: Intelligent-University-Visit-System
  datasource:
    url: ${UNITOUR_MYSQL_URL:jdbc:mysql://localhost:3307/uni_tour}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${UNITOUR_MYSQL_USERNAME:root}
    password: ${UNITOUR_MYSQL_ROOT_PASSWORD}
  data:
    redis:
      host: ${UNITOUR_REDIS_HOST:localhost}
      port: ${UNITOUR_REDIS_PORT:6379}

#配置日志输出
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
